### ISSUE TITLE
Abstractions

### ISSUE THREAD

**Issue by ivario123** [ivario123/NGAC_ABE#11]
# Abstractions

Previously I recommended hierarchical abstractions like
```python
class SuperObject:
       ....
       ....
       def get_type(self)->str:
            ....
class SomeOtherObject(SuperObject):
       ....
       ....
def what_type_is_the_object(obj:SuperObject):
     if obj.get_type() == "SomeOtherObject":
       return SomeOtherObject
```

After writing some code using this structure I find it clumsy and un-ergonomic since you always have to handle both types and strings representing types.
## New and improved
A better solution is doing something like:
```python
class SuperObject:
      """ 
      Empty class, just used for typing
      """
      pass

class SomeOtherObject(SuperObject):
      """
      A more powerful object that can do more things
      """
       ....
       .... # Whatever we need

def what_type_is_the_object(obj:SuperObject):
     if type(Obj) == SomeOtherObject # Here we don't need to handle strings at all
        ... # Do some cool things
```

I think that we should rework the NGAC types and future ABE to use the second paradigm. What do you think? @sanlju  @Klas-Norling @Leohemmingsson

**Comment by Leohemmingsson** [comment]
I agree, it looks clean and is also written very pythonic

**Comment by ivario123** [comment]
If we want to use this method instead I think that we should make a new PR with a refactoring of all the NGAC abstractions. @sanlju Do you want to work on that?

To do:
- [ ] Review and Merge pr #10 
- [ ] Make new branch for refactoring
- [ ] Refactor all classes in ngac_types to follow the new paradigm
- [ ] Make new PR detailing work
- [ ] Review and merge

**Comment by ivario123** [comment]
this has already been implemented, closing
